name: CI/CD Pipeline
# Trigger the workflow
on:
  # manually
  workflow_dispatch:
  # on push to the master branch
  push:
    branches:
      - master
  # on pull request to the master branch
  pull_request:
    branches:
      - master
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Set up JDK 11 and cache for Gradle dependencies
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Run Tests
        run: ./gradlew build --no-daemon
