name: CI/CD Pipeline
on:
  workflow_dispatch:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Run Tests
        run: ./gradlew build --no-daemon
